// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/military.proto

package protov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MilitaryEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Country         string                 `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	WarplanesInAir  int32                  `protobuf:"varint,2,opt,name=warplanes_in_air,json=warplanesInAir,proto3" json:"warplanes_in_air,omitempty"`
	WarshipsInWater int32                  `protobuf:"varint,3,opt,name=warships_in_water,json=warshipsInWater,proto3" json:"warships_in_water,omitempty"`
	Timestamp       int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MilitaryEvent) Reset() {
	*x = MilitaryEvent{}
	mi := &file_proto_military_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MilitaryEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MilitaryEvent) ProtoMessage() {}

func (x *MilitaryEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_military_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MilitaryEvent.ProtoReflect.Descriptor instead.
func (*MilitaryEvent) Descriptor() ([]byte, []int) {
	return file_proto_military_proto_rawDescGZIP(), []int{0}
}

func (x *MilitaryEvent) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *MilitaryEvent) GetWarplanesInAir() int32 {
	if x != nil {
		return x.WarplanesInAir
	}
	return 0
}

func (x *MilitaryEvent) GetWarshipsInWater() int32 {
	if x != nil {
		return x.WarshipsInWater
	}
	return 0
}

func (x *MilitaryEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_military_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_military_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_military_proto_rawDescGZIP(), []int{1}
}

func (x *Ack) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_military_proto protoreflect.FileDescriptor

const file_proto_military_proto_rawDesc = "" +
	"\n" +
	"\x14proto/military.proto\x12\bproto.v1\"\x9d\x01\n" +
	"\rMilitaryEvent\x12\x18\n" +
	"\acountry\x18\x01 \x01(\tR\acountry\x12(\n" +
	"\x10warplanes_in_air\x18\x02 \x01(\x05R\x0ewarplanesInAir\x12*\n" +
	"\x11warships_in_water\x18\x03 \x01(\x05R\x0fwarshipsInWater\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\x1d\n" +
	"\x03Ack\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2I\n" +
	"\x0fMilitaryService\x126\n" +
	"\fPublishEvent\x12\x17.proto.v1.MilitaryEvent\x1a\r.proto.v1.AckB:Z8github.com/HenryMaldonado27/military-proto/proto;protov1b\x06proto3"

var (
	file_proto_military_proto_rawDescOnce sync.Once
	file_proto_military_proto_rawDescData []byte
)

func file_proto_military_proto_rawDescGZIP() []byte {
	file_proto_military_proto_rawDescOnce.Do(func() {
		file_proto_military_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_military_proto_rawDesc), len(file_proto_military_proto_rawDesc)))
	})
	return file_proto_military_proto_rawDescData
}

var file_proto_military_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_military_proto_goTypes = []any{
	(*MilitaryEvent)(nil), // 0: proto.v1.MilitaryEvent
	(*Ack)(nil),           // 1: proto.v1.Ack
}
var file_proto_military_proto_depIdxs = []int32{
	0, // 0: proto.v1.MilitaryService.PublishEvent:input_type -> proto.v1.MilitaryEvent
	1, // 1: proto.v1.MilitaryService.PublishEvent:output_type -> proto.v1.Ack
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_military_proto_init() }
func file_proto_military_proto_init() {
	if File_proto_military_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_military_proto_rawDesc), len(file_proto_military_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_military_proto_goTypes,
		DependencyIndexes: file_proto_military_proto_depIdxs,
		MessageInfos:      file_proto_military_proto_msgTypes,
	}.Build()
	File_proto_military_proto = out.File
	file_proto_military_proto_goTypes = nil
	file_proto_military_proto_depIdxs = nil
}
