// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: military.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MilitaryEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MilitaryEvent) Reset() {
	*x = MilitaryEvent{}
	mi := &file_military_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MilitaryEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MilitaryEvent) ProtoMessage() {}

func (x *MilitaryEvent) ProtoReflect() protoreflect.Message {
	mi := &file_military_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MilitaryEvent.ProtoReflect.Descriptor instead.
func (*MilitaryEvent) Descriptor() ([]byte, []int) {
	return file_military_proto_rawDescGZIP(), []int{0}
}

func (x *MilitaryEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MilitaryEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_military_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_military_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_military_proto_rawDescGZIP(), []int{1}
}

func (x *Ack) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_military_proto protoreflect.FileDescriptor

const file_military_proto_rawDesc = "" +
	"\n" +
	"\x0emilitary.proto\x12\bmilitary\"3\n" +
	"\rMilitaryEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"\x1d\n" +
	"\x03Ack\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2I\n" +
	"\x0fMilitaryService\x126\n" +
	"\fPublishEvent\x12\x17.military.MilitaryEvent\x1a\r.military.AckB\x16Z\x14military-proto/protob\x06proto3"

var (
	file_military_proto_rawDescOnce sync.Once
	file_military_proto_rawDescData []byte
)

func file_military_proto_rawDescGZIP() []byte {
	file_military_proto_rawDescOnce.Do(func() {
		file_military_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_military_proto_rawDesc), len(file_military_proto_rawDesc)))
	})
	return file_military_proto_rawDescData
}

var file_military_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_military_proto_goTypes = []any{
	(*MilitaryEvent)(nil), // 0: military.MilitaryEvent
	(*Ack)(nil),           // 1: military.Ack
}
var file_military_proto_depIdxs = []int32{
	0, // 0: military.MilitaryService.PublishEvent:input_type -> military.MilitaryEvent
	1, // 1: military.MilitaryService.PublishEvent:output_type -> military.Ack
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_military_proto_init() }
func file_military_proto_init() {
	if File_military_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_military_proto_rawDesc), len(file_military_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_military_proto_goTypes,
		DependencyIndexes: file_military_proto_depIdxs,
		MessageInfos:      file_military_proto_msgTypes,
	}.Build()
	File_military_proto = out.File
	file_military_proto_goTypes = nil
	file_military_proto_depIdxs = nil
}
